massageProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('massageProject.main_app.urls')),
    path('accounts/', include('massageProject.accounts.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

massageProject/main_app/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver

class Massage(models.Model):
    name = models.CharField(max_length=80)
    description = models.TextField()
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2
    )
    duration_in_minutes = models.IntegerField()
    short_description = models.CharField(max_length=255)
    image = models.ImageField(upload_to='massages/')
    home_page = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Masseur(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='masseurs/')
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()
    working_hours = models.TextField()

class MessageStudio(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    main_image = models.ImageField(upload_to='studios/')
    address = models.CharField(max_length=255)

class MessageReservation(models.Model):
    massage = models.ForeignKey(
        Massage,
        on_delete=models.CASCADE,
        related_name='reservations'
    )

    masseur = models.ForeignKey(
        'Masseur',
        on_delete=models.CASCADE,
        related_name='reservations',
        blank=True,
    )

    user = models.ForeignKey(
        'accounts.CustomUser',
        on_delete=models.CASCADE,
        related_name='reservations',
        blank=True,
    )

    time = models.TimeField()
    date = models.DateField()
    updated_at = models.DateTimeField(auto_now=True)
    additional_text = models.TextField(default='', blank=True)

@receiver(pre_save, sender=MessageReservation)
def set_masseur(sender, instance, **kwargs):
    instance.masseur = Masseur.objects.first()

class Gallery(models.Model):
    images = models.ManyToManyField('Image', related_name='galleries', through='GalleryImage')

class Image(models.Model):
    image = models.ImageField(upload_to='studios/gallery/')
    alt_text = models.CharField(max_length=255)

    def __str__(self):
        return self.alt_text

class GalleryImage(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)
    image = models.ForeignKey(Image, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('gallery', 'image')

class HomePage(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    gallery = models.OneToOneField(
        Gallery,
        on_delete=models.CASCADE,
        related_name='home_page'
    )

class Comment(models.Model):
    author = models.CharField(
        max_length=30,
    )

    content = models.TextField()

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

templates/pages/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="about-me">
    <div class="description">
        <h2>За мен и моето студио</h2>
        <div class="about-content">
            <div class="photo-info-container">
                <!-- Photo Section -->
                <div class="photo-wrapper">
                    <img src="{{ masseur.image.url }}" alt="Masseur's Photo">
                </div>
                <!-- Info Section -->
                <div class="info-section">
                    <p>
                        {{ masseur.description }}
                    </p>
                    <p>
                        {{ studio.description }}
                    </p>
                </div>
            </div>
{#            <!-- Certificate Section -->#}
{#            <div class="certificate-section">#}
{#                <div class="certificate">#}
{#                    <img src="{% static 'images/certificate.png' %}" alt="Certificate">#}
{#                </div>#}
{#            </div>#}
        </div>
    </div>
</section>

<section class="comments">
    <div class="description">
        <h2>Коментари</h2>
        <div class="comment-carousel">
            <div class="carousel-wrapper">
                {% for comment in comments %}
                <div class="carousel-item">
                    <strong>{{ comment.author }}</strong>
                    <p>{{ comment.content }}</p>
                </div>
                {% empty %}
                <div class="carousel-item">
                    <strong>Няма коментари</strong>
                    <p>Бъди първенец и остави твоето мнение</p>
                </div>
                {% endfor %}
            </div>
            <button class="carousel-btn prev-btn">&laquo;</button>
            <button class="carousel-btn next-btn">&raquo;</button>
        </div>
        {% if perms.app_name.add_comment %}
            <form class="comment-form" method="post">
                {% csrf_token %}
                <h3>Остави коментар</h3>
                {% if user.is_authenticated %}
                <div class="form-group">
                    {{ form.content }}
                </div>
                <button type="submit" class="btn-primary">Качи коментара</button>
                 {% else %}
                    <p>Влезте в профила си, за да оставите коментар.<b><a href="#">Кликнете тук</a></b></p>
                {% endif %}
            </form>
        {% else %}
            <p>Вие нямате разрешение да оставяте коментари.</p>
        {% endif %}
    </div>
</section>

<script src="{% static 'js/comments.js' %}"></script>
{% endblock %}

templates/pages/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Hero Section -->
    <section class="hero-section">
        <div class="hero-content">
            <h1>{{ page.title }}</h1>
            <p>{{ page.description }}</p>
        </div>
    </section>

    <!-- Carousel Section -->
    {% if images %}
    <section class="carousel-section">
        <div class="carousel">
            {% for image in images %}
                <div class="carousel-slide active">
                    <img src="{{ image.image.url }}" alt="{{ image.alt_text }}">
                </div>
            {% endfor %}
            <button class="carousel-btn prev" onclick="prevSlide()">&#10094;</button>
            <button class="carousel-btn next" onclick="nextSlide()">&#10095;</button>
        </div>
    </section>
    {% endif %}

    <!-- Offer Cards Section -->
    <section class="offers">
        <div class="container">
            <h2>Предпочитани масажи</h2>
            <div class="card-container">
                {% for m in massages %}
                    <div class="card">
                        <h3>{{ m.name }}</h3>
                        <p>
                            {{ m.short_description }}
                        </p>
                        <a href="{% url 'reservation_page' pk=m.pk %}" class="btn">Направи резервация</a>
                        <a href="{% url 'massage_detail' pk=m.pk %}" class="btn btn-primary">Научете повече</a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    
    {% include 'partials/working_hours.html' %}
    <script src="{% static 'js/carousel.js' %}"></script>
    
{% endblock %}

templates/pages/massage_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="blog-container">
    <div class="blog-header">
        <img src="{{ massage.image.url }}" alt="{{ massage.name }}" class="blog-image">
    </div>
    <div class="blog-content">
        <h1 class="blog-title">{{ massage.name }}</h1>
        <div class="blog-description">
            <p>{{ massage.description }}</p>
        </div>
        <div class="blog-details">
            <p><strong>Цена:</strong> {{ massage.price }}лв</p>
            <p><strong>Продължителност:</strong> {{ massage.duration_in_minutes }} minutes</p>
        </div>
        <a href="{% url 'reservation_page' pk=massage.pk %}" class="btn">Направи резервация</a>
    </div>
</div>
{% endblock %}

templates/pages/massages_page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <h1>Предлагани масажи</h1>
        <div class="cards">
            {% for m in massages %}
                <div class="card">
                    <img src="{{ m.image.url }}" alt="Swedish Massage">
                    <div class="card-content">
                        <h2 class="card-title">{{ m.name }}</h2>
                        <p class="card-description">{{ m.short_description }}</p>
                        <a href="{% url 'massage_detail' pk=m.pk %}" class="btn">Научете повече</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/pages/my_profile.html
{% extends "base.html" %}

{% block content %}
<section class="reservation-page">
    <div class="description">
        <h2>{{ title }}</h2>
        {% if reservations %}
            <div class="reservation-table">
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Дата</th>
                            <th>Час</th>
                            <th>Вид</th>
                            <th>Съобщение</th>
                            <th>Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for reservation in reservations %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ reservation.date }}</td>
                                <td>{{ reservation.time }}</td>
                                <td>{{ reservation.massage }}</td>
                                <td>{{ reservation.additional_text }}</td>
                                <td>
                                    <a href="{% url 'delete_reservation' reservation.id %}" class="btn-danger">Отмени</a>
                                    <a href="{% url 'edit_reservation' reservation.id %}" class="btn-edit">Промени</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
            <p>Вие нямате резервации</p>
        {% endif %}
    </div>
</section>
    
{% if reservations %}
    {% include 'partials/working_hours.html' %}
{% endif %}

{% endblock %}

templates/pages/reservation.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="hero-section">
    <div class="hero-content">
        <h1>Резервирайте своя масаж</h1>
        <p>Подарете си релаксация и възстановяване с нашите професионални масажни услуги.</p>
    </div>
</section>

{% if user.is_authenticated %}
    <section class="reservation-form">
        <div class="description">
            <h2>Запазете час</h2>
            <p>Попълнете формуляра по-долу, за да запазите час за масаж. Очакваме Ви с нетърпение!</p>
            <form class="form-container" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="massage">Тип масаж</label>
                    <select id="massage" name="massage" required>
                        {% for massage in form.fields.massage.queryset %}
                            <option value="{{ massage.id }}" {% if form.massage.value == massage.id %}selected{% endif %}>
                                {{ massage.name }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="date">Предпочитана дата</label>
                    <input type="date" id="date" name="date"
                        value="{{ form.date.value|default:'' }}" required>
                </div>
                <div class="form-group">
                    <label for="time">Предпочитано време</label>
                    <select id="time" name="time" required>
                        <option value="" disabled {% if not form.time.value %}selected{% endif %}>
                            Изберете време
                        </option>
                        <option value="09:00" {% if form.time.value == '09:00' %}selected{% endif %}>
                            09:00 ч.
                        </option>
                        <option value="10:00" {% if form.time.value == '10:00' %}selected{% endif %}>
                            10:00 ч.
                        </option>
                        <option value="11:00" {% if form.time.value == '11:00' %}selected{% endif %}>
                            11:00 ч.
                        </option>
                        <option value="13:00" {% if form.time.value == '13:00' %}selected{% endif %}>
                            13:00 ч.
                        </option>
                        <option value="15:00" {% if form.time.value == '15:00' %}selected{% endif %}>
                            15:00 ч.
                        </option>
                        <option value="17:00" {% if form.time.value == '17:00' %}selected{% endif %}>
                            17:00 ч.
                        </option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="additional_text">Допълнителни бележки</label>
                    <textarea id="additional_text" name="additional_text"
                              placeholder="Специални изисквания или притеснения">{{ form.additional_text.value|default:'' }}</textarea>
                </div>
                <button type="submit" class="btn-primary">Резервирайте сега</button>
            </form>
        </div>
    </section>
{% else %}
    <section class="unathenticted reservation-form">
        <div class="description">
            <h2>Запазете час</h2>
            <p>За да направите резервация, моля <a href="{% url 'register' %}">регистрирайте се</a> или <a href="{% url 'login' %}">влезте</a>.</p>
        </div>
    </section>
{% endif %}
    
{% endblock %}